HiEventsDev/Hi.Events

- SECURITY.md
- backend/app/Services/Handlers/Order/CompleteOrderHandler.php
Thanks to @td00 for flagging this.
> Fix ability to select tickets unrelated to your order

- Dockerfile.all-in-one
This small PR fixes `startup.sh` file not being found in when building on Windows (Fixes https://github.com/HiEventsDev/hi.events/issues/5 and [Reddit comment](https://www.reddit.com/r/selfhosted/comments/1dabulx/comment/l7mci9p/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button))
The reason that this was occurring is because Windows saves the file with Windows line endings instead of the Unix line endings required by the Docker container. This is easily remedied by running `dos2unix` in the Dockerfile so that it doesn't need to be changed manually when building on Windows.
> Fix startup.sh not found when building on Windows

- README.md
- docker/all-in-one/docker-compose.yml
- docker/backend/docker-compose.yml
- docker/development/docker-compose.dev.yml
- docker/frontend/docker-compose.yml
1. The "version" Tag in the compose file is [obsolete](https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element-obsolete)
2. `docker-compose` is from Compose-V1 but this stopped receiving updates, so this should be migrated to [V2](https://docs.docker.com/compose/migrate/)
> feat: update to current docker standards

- backend/config/mail.php
- frontend/src/components/common/EventDateRange/index.tsx
- frontend/src/components/forms/TicketForm/index.tsx
- frontend/src/components/layouts/EventHomepage/EventInformation/index.tsx
- frontend/src/utilites/dates.ts
No end date
Multi day
Same day
> Improve date and time display on event page

- README.md
[Zeabur](https://zeabur.com) is a cloud hosting platform. I've created a template for users to deploy Hi.events with one click on Zeabur. 
Template: https://zeabur.com/templates/8DIRY6
Preview: https://tnbteb.zeabur.app/event/1/zeabur
> docs: add deploy to Zeabur as another one-click solution

- frontend/src/components/common/WidgetEditor/index.tsx
- frontend/src/embed/widget.js
> Widget JS doesn't details domain correctly

- docker/all-in-one/nginx/nginx.conf
Currently, any images added to events larger than 1MB will result in an error: `client intended to send too large body`. This is because the default [client_max_body_size] is 1 MB. This commit increases that limit to 20 MB so that larger images can be uploaded.
[client_max_body_size]: https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
> Allow larger files to be uploaded via the API

- backend/app/Services/Domain/Order/OrderCreateRequestValidationService.php
- frontend/src/components/common/NumberSelector/index.tsx
- frontend/src/components/routes/ticket-widget/SelectTickets/Prices/Tiered/index.tsx
Just a variety of QoL changes regarding edge cases for ticket quantities (mostly frontend, one backend change regarding buying fewer than the minimum if there aren't enough tickets to reach the minimum).
1. Create shared values for all tiers of a given ticket, to ensure mins/maxes are adhered to and the overall maximum won't be exceeded.
1. If a given tier has less available than the order minimum, incrementing will change the value for that tier to the tickets available. If you then increment another ticket tier, it will increase it only to the level that brings the order value up to the order minimum. (Example: two tiers, 5-ticket minimum. Tier 1 has 3 tickets remaining, and Tier 2 has no limit. If you increment Tier 1 from 0, it will increase to 3. If you then increment Tier 2, it will …
> Improve ticket quantity edge cases

- frontend/package.json
- frontend/src/components/common/Editor/Controls/InsertImageControl/index.tsx
- frontend/src/components/common/Editor/Extensions/ImageResizeExtension/index.tsx
- frontend/src/components/common/Editor/index.tsx
- frontend/yarn.lock
This PR tackles the image extension for issue #246
I added Image extension, so users can add images to places where full rich text editor is used as shown in the screenshots
> feat: add image extension to rich text editor

- backend/config/app.php
- backend/resources/views/vendor/mail/html/message.blade.php
This adds env variable that changes the webpage the logo will lead to when clicking on it in an email.
In most cases, we don't want customers to be routed to our events organizer login page when they click on the logo in an email. Instead, they can set another page (i.e. instead of events.mysite.com, they can just be sent to mysite.com)
> Allow the header of emails to link to a webpage other than the app URL

- backend/resources/views/emails/orders/attendee-ticket.blade.php
- backend/resources/views/emails/orders/order-cancelled.blade.php
- backend/resources/views/emails/orders/order-failed.blade.php
- backend/resources/views/emails/orders/order-refunded.blade.php
- backend/resources/views/emails/orders/payment-success-but-order-expired.blade.php
- backend/resources/views/emails/orders/summary.blade.php
- backend/resources/views/vendor/mail/html/message.blade.php
- frontend/src/components/common/EventDocumentHead/index.tsx
This is a minor change that modifies some text in emails and in the title of event pages.
1. It ensures all emails end with the app name, and normalizes the format of that section of the email
2. Changes the default email footer to "© `<year>` `<app-name>` | Powered by Hi.Events" with Hi.Events linked to https://hi.events?utm_source=app-email-footer. My thinking is that the actual content of the email may not be copyrighted to Hi.Events; and it changes the footer to the "Powered by" verbiage, as that's [what is in the LICENCE](https://github.com/HiEventsDev/Hi.Events/blob/develop/LICENCE#L1-L8), so it makes it consistent with the license and elsewhere in the code.
3. Changes the event page title to end with the organizer name instead of "Hi.Events" (i.e. "My Great Event | Cool Theater"). …
> Various semantic changes in email text, footer, and event page

- frontend/src/components/routes/ticket-widget/SelectTickets/Prices/Tiered/index.tsx
- frontend/src/components/routes/ticket-widget/SelectTickets/index.tsx
- frontend/src/styles/widget/default.scss
On Safari (on iPhone), the right arrow is being converted to a ➡️ emoji, which is not desirable (FWIW, the down arrow is fine 🤷🏻‍♂️).
This changes the arrows from unicode arrows to an Icon, which also animates as the tickets open / close.
Also, fixes the inverted boolean logic around `ticketIsCollapsed`. Same exact functionality, I just had the boolean logic backwards on all of it.
Also, better aligns all the elements in the ticket title button.
---
Also fixes some alignment of ticket elements to ensure that the ticket counter is always on the right. If wrapping is necessary, the name of the tier should wrap.
BEFORE:
AFTER:
---
> Prevent arrow conversion to emoji; fix alignment of ticket elements

- frontend/src/components/routes/product-widget/CollectInformation/index.tsx
- frontend/src/components/routes/product-widget/Payment/index.tsx
Some strings on the frontend were missing translation wrapping, so I added it.
> Small Fix: Add wrap for translatable strings

- backend/composer.json
- backend/composer.lock
The php dependency "druc/laravel-langscanner" got moved into development dependencies. Fixes #479
- [x ] I have read the contributing guidelines.
- [x ] My code is of good quality and follows the coding standards of the project.
- [x ] I have tested my changes, and they work as expected.
> Fix remove dev dependency laravel-langscanner from production

- frontend/server.js
Phusion Passenger application server, which is used by Plesk, can't handle top-level await. Wrapping all code in server.js into an async function and calling it fixes that. Fixes #481
> Fix top-level await in server.js causes error in Phusion Passenger

- backend/app/DomainObjects/Enums/ImageTypes.php
- backend/app/Http/Actions/Images/CreateImageAction.php
- backend/app/Http/Request/Image/CreateImageRequest.php
- backend/app/Services/Application/Handlers/Event/CreateEventImageHandler.php
- backend/app/Services/Application/Handlers/Event/DTO/CreateEventImageDTO.php
- backend/app/Services/Application/Handlers/Images/CreateImageHandler.php
- backend/app/Services/Application/Handlers/Images/DTO/CreateImageDTO.php
- backend/app/Services/Application/Handlers/Organizer/CreateOrganizerHandler.php
- backend/app/Services/Domain/Event/CreateEventImageService.php
- backend/app/Services/Domain/Image/ImageUploadService.php
- backend/app/Services/Infrastructure/Image/ImageStorageService.php
- backend/app/Validators/Rules/RulesHelper.php
- backend/routes/api.php
- backend/tests/Unit/Services/Application/Handlers/Images/CreateImageHandlerTest.php
- backend/tests/Unit/Services/Domain/Image/ImageUploadServiceTest.php
- frontend/package.json
- frontend/server.js
- frontend/src/api/event.client.ts
- frontend/src/api/image.client.ts
- frontend/src/components/common/Editor/Controls/InsertImageControl/index.tsx
- frontend/src/components/common/Editor/Extensions/ImageResizeExtension/index.tsx
- frontend/src/mutations/useUploadEventImage.ts
- frontend/src/mutations/useUploadImage.ts
- frontend/src/types.ts
- frontend/yarn.lock
Fix env variables from .env are missing in server.js (#487)
All uploading images to event descriptions (#512)
> PRs #487 and #512

- frontend/src/entry.client.tsx
- frontend/src/locales.ts
Partially fixes #525. The changes dynamically import the language. The current method loads the language when the application is ready to display the ui. With the new approach that is too late to start downloading the language js file. Thats why i call the method in `initClientApp()`.
This improves performance, but further optimization is possible. Currently, my changes don't affect the existing `dynamicActivationLocale()` call because I'm unsure of the impact of `setLoaded()`. We're also downloading a large index.js file, which then triggers numerous imports. This forces the browser to wait for the initial file before discovering and requesting other necessary files, such as the language file. 
To address this, we should flatten the dependency structure. Instead of a single `<script>` …
> Fix downloading all languages

- backend/app/Services/Domain/Payment/Stripe/EventHandlers/PaymentIntentSucceededHandler.php
This PR ensures that the `application_fee_amount` value from Stripe's `PaymentIntent` always defaults to `0` if it is not set. This prevents potential issues with null values and guarantees consistent handling of application fees throughout the payment processing workflow.
- Used the null coalescing operator (`?? 0`) when accessing `$paymentIntent->application_fee_amount` in all relevant places.
- This ensures that if Stripe does not provide an `application_fee_amount`, the system will safely use `0` as the default.
- Improves reliability and prevents errors related to missing or null fee amounts.
This change improves the robustness of the payment handling logic by ensuring that all calculations and records involving the application fee are based on a valid integer value, even if Stripe …
> Fix application fee amount handling

- backend/app/Helper/Url.php
Updating the `getCdnUrl` helper to fall back to generating a URL using the filesystem disk if the `CDN_URL` environment variable is not set. This allows us to still use S3 resource links if a CDN Url is not in place. Fixes #616.
* `backend/app/Helper/Url.php`: Updated the `getCdnUrl` method to:
- Check for the `CDN_URL` environment variable and use this if it is set.
- Fall back to generating a URL using the specified or default filesystem disk (`public`) if the CDN URL is not configured. see: https://laravel.com/docs/11.x/filesystem#file-urls
I have discovered a typo `'cnd_url'` in `app.php` which has not been resolved in this PR.
> Use Laravel Filesystem URL Generator for Images

- docker/all-in-one/.env
- docker/all-in-one/README.md
- docker/all-in-one/docker-compose.yml
- docker/all-in-one/supervisor/supervisord.conf
This pull request adds a new program configuration to the `supervisord.conf` to ensure that `php artisan queue:work` is ran automatically on startup. The configuration ensures proper logging and automatic restart behavior for the queue worker process. Fixes #270, #506.
* [`docker/all-in-one/supervisor/supervisord.conf`](diffhunk://#diff-9fe669a8ee4481899240c861c9b8288609e1d4efddb88d168facca9f8640d161R38-R48): Added a `[program:laravel-queue-worker]` section to run Laravel's queue worker with specific parameters, including `autostart`, `autorestart`, logging to standard output and error, and setting log file size limits to zero for unlimited logging.
> Add Laravel queue worker to startup

- backend/app/Services/Application/Handlers/EventSettings/PartialUpdateEventSettingsHandler.php
Users were unable to save empty values for the maps URL field in event settings. When attempting to clear an existing maps URL, the system would ignore the empty value and revert to the previously saved URL upon save.
Fixes [🐛 Cannot save empty maps URL in event settings #624](https://github.com/HiEventsDev/Hi.Events/issues/624)
The issue occurred in the `PartialUpdateEventSettingsHandler.php` file where the `maps_url` field was being handled using the null coalescing operator (`??`):
```php
'maps_url' => $eventSettingsDTO->settings['maps_url'] ?? $existingSettings->getMapsUrl(),
```
In PHP, this operator treats empty strings as falsy values, causing the system to fall back to the existing value when users attempted to save an empty string.
Updated the code to use `array_key_exists()` …
> Fix: Allow empty strings for event settings maps_url

- backend/app/Http/Request/ProductCategory/UpsertProductCategoryRequest.php
- backend/database/migrations/2025_06_24_055432_change_proudct_category_description_type.php
- frontend/src/components/forms/ProductCategoryForm/index.tsx
- frontend/src/components/routes/product-widget/SelectProducts/index.tsx
> Fix product category description not showing
